#!/usr/bin/env python
#

import sys
import hss_utils.rosetta
import hss_utils.rosetta.services

try:
    envs = [hss_utils.rosetta.get_environment(sys.argv[1])]
    if not envs:
        sys.exit(-1)
    st_config = hss_utils.rosetta.services.st_config_for(envs[0])
    if st_config.raw['cabinets']:
        print 'CBA_run_install_%sHSS' % ('' if st_config.raw['cabinets'][0]['type'] == 'CBA' else 'v')
        sys.exit(0)
except Exception as e:
    pass
    
sys.exit(-1)

CBA