#!/usr/bin/env python
#

import sys
import hss_utils.rosetta
import hss_utils.rosetta.services

try:
    envs = [hss_utils.rosetta.get_environment(sys.argv[1])]
    if not envs:
        sys.exit(-1)
    st_config = hss_utils.rosetta.services.st_config_for(envs[0])
    if st_config.generators:
        print st_config.generators[0]
        sys.exit(0)
except Exception as e:
    pass
    
sys.exit(-1)

